[buildPlans.PragmataPro]
family = "PragmataPro"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

hintParams = ["-a", "qqq"]

    [buildPlans.PragmataPro.widths.normal]
    shape = 500
    menu  = 5
    css   = "normal"

    [buildPlans.PragmataPro.metricOverride]
    leading = 1100
    xHeight = 550

    [buildPlans.PragmataPro.ligations]
    inherits="default-calt"
    enables = [
        "eqslasheq",
        "kern-dotty",
        "kern-bars",
        "llggeq",
         "--fast-chaining--"
    ]
    disables = ["slash-asterisk"]

    [buildPlans.PragmataPro.variants]
    inherits = "ss08"

    [buildPlans.PragmataPro.weights.regular]
    shape = 425
    menu = 400
    css = 400

    [buildPlans.PragmataPro.weights.semibold]
    shape = 600
    menu = 600
    css = 600
    
    [buildPlans.PragmataPro.weights.bold]
    shape = 800
    menu = 700
    css = 700

    [buildPlans.PragmataPro.weights.black]
    shape = 900
    menu = 900
    css = 900

    [buildPlans.PragmataPro.slopes]
    upright = "default.Upright"
    italic = "default.Italic"
